#' @title Combine Parameter Tables
#'
#' @description The c-method for
#' `partables`-class object.
#'
#' @details
#' It is the 'c' method of
#' `partables`-class objects.
#'
#' Each object must be (a) a
#' `partables`-class object,
#' (b) a `model_set`-class object,
#' (b) a `lavaan`-class object,
#' (c) a parameter table of
#' the class `lavaan.data.frame()`,
#' usually generated by
#' [lavaan::parameterTable()].
#' Other objects will be discarded.
#'
#' Names will be used when combining
#' objects. If two objects have the same
#' names, then only the first one will be
#' retained. No warning message will be
#' issued. Users are encouraged to
#' explicitly name all objects carefully.
#'
#' Note that, to invoke this method,
#' the first object must be a
#' `partables` object.
#'
#' @return
#' A `partables`-class objects with
#' all the objects supplied combined
#' together. If an object is
#' a `lavaan`-class object, its
#' parameter table will be retrieved
#' by [lavaan::parameterTable()].
#' If an object is a `model_set`-class
#' object, the stored `partables`-class
#' object will be retrieved.
#'
#' @param ... An arbitrary number of
#' objects. All invalid objects (see
#' details) will be discarded. If an
#' object is named and is not
#' `partables` object, its name will be
#' used.
#'
#' @author Shu Fai Cheung <https://orcid.org/0000-0002-9871-9448>
#'
#' @examples
#'
#' # TO UPDATE
#'
#' library(lavaan)
#'
#'
#' moda <-
#' "
#' x3 ~ a*x1 + b*x2
#' x4 ~ a*x1
#' ab := a*b
#' "
#'
#' fita <- sem(moda, dat_path_model, fixed.x = TRUE)
#'
#' outa <- model_set(fita,
#'                   progress = FALSE,
#'                   parallel = FALSE)
#'
#' modb <-
#' "
#' x3 ~ a*x1 + b*x2
#' x4 ~ a*x2
#' ab := a*b
#' "
#'
#' fitb <- sem(modb, dat_path_model, fixed.x = TRUE)
#'
#' outb <- model_set(fitb,
#'                   progress = FALSE,
#'                   parallel = FALSE)
#'
#' mod2 <-
#' "
#' x2 ~ 0*x3 + 0*x4
#' x1 ~ 0*x3
#' "
#' fit2 <- sem(mod2, dat_path_model)
#'
#' mod3 <-
#' "
#' x2 ~ x3 + 0*x4
#' x1 ~ x3
#' "
#' fit3 <- sem(mod3, dat_path_model)
#'
#' out <- c(outa$models, user2 = fit2, outb$models, user3 = fit3)
#' out
#'
#' out2 <- c(outa, user2 = fit2, outb$models, user3 = fit3)
#' out2
#'
#' out3 <- c(outa, user2 = fit2, outb, user3 = fit3)
#' out3
#'
#' @export

c.partables <- function(...) {
    ddd <- list(...)
    ddd_names <- sapply(as.list(match.call()[-1]), deparse)
    if (!is.null(names(ddd_names))) {
        i <- which(sapply(names(ddd_names), function(x) {nchar(x) > 0}))
        if (length(i) > 0) {
            ddd_names[i] <- names(ddd_names)[i]
            ddd_names <- unname(ddd_names)
          }
      }
    is_partables <- sapply(ddd,
                           inherits,
                           what = "partables")
    is_lavaan <- sapply(ddd,
                        inherits,
                        what = "lavaan")
    is_ptable <- sapply(ddd,
                        inherits,
                        what = "lavaan.data.frame")
    is_model_set <- sapply(ddd,
                           inherits,
                           what = "model_set")
    if (any(is_lavaan)) {
        p <- which(is_lavaan)
        for (i in p) {
            tmp <- list(lavaan::parameterTable(ddd[[i]]))
            names(tmp) <- ddd_names[i]
            ddd[[i]] <- tmp
          }
      }
    if (any(is_ptable)) {
        p <- which(is_ptable)
        for (i in p) {
            tmp <- list(ddd[[i]])
            names(tmp) <- ddd_names[i]
            class(tmp) <- c("partables", class(tmp))
            ddd[[i]] <- tmp
          }
      }
    if (any(is_model_set)) {
        p <- which(is_model_set)
        for (i in p) {
            ddd[[i]] <- ddd[[i]]$models
          }
      }
    is_valid <- is_ptable |
                is_lavaan |
                is_partables |
                is_model_set
    ddd <- ddd[is_valid]
    out <- c_partables(ddd)
  }

#' @describeIn c.partables The c-method for `model_set` objects.
#'   It will replace the first object by the stored
#'   partables and then call the c-method of `partables` objects.
#' @export

c.model_set <- function(...) {
    ddd <- list(...)
    ddd[[1]] <- ddd[[1]]$models
    ddd_names <- sapply(as.list(match.call()[-1]), deparse)
    if (!is.null(names(ddd_names))) {
        i <- which(sapply(names(ddd_names), function(x) {nchar(x) > 0}))
        if (length(i) > 0) {
            ddd_names[i] <- names(ddd_names)[i]
            ddd_names <- unname(ddd_names)
          }
      }
    names(ddd) <- ddd_names
    do.call(c.partables, ddd)
  }

#' @noRd

c_partables <- function(ddd) {
    if (length(ddd) == 1) {
        return(ddd[[1]])
      }
    out <- ddd[[1]]
    for (i in seq_along(ddd)[-1]) {
        ddd_i <- ddd[[i]]
        i_names <- names(ddd_i)
        i_names <- setdiff(i_names, names(out))
        if (length(i_names) == 0) next
        for (j in i_names) {
            out[[j]] <- ddd_i[[j]]
          }
      }
    out
  }