#' @title Fit a List of Models
#'
#' @description Fit a list of models.
#'
#' @details (TO-DO)
#'
#' @param model_list A list of parameter
#' tables to be used by
#' [lavaan::lavaan()] or [update()].
#' Usually generated by [get_add()] or
#' [get_drop()].
#'
#' @param sem_out The output from an
#' structural equation modeling
#' function. Currently support
#' [lavaan::lavaan-class] only. Usually
#' the one used in [get_add()] or
#' [get_drop()] to generate the list of
#' models.
#'
#' @return A list with the following elements:
#'
#' * `fit`: A named list of
#'    [lavaan::lavaan()] output objects or
#'    [update()] for fitting a model with
#'    the added parameters.
#'
#' * `change`: A numeric vector, of the
#'    same length as `fit`. The change
#'    in model df for each fit. A
#'    positive number denotes one less
#'    free parameter. A negative number
#'    denotes one more free parameter or
#'    one less constraint.
#'
#' * `converged`: A named vector of
#'    boolean values, of the same length
#'    as `fit`. Indicates whether each
#'    fit converged or not.
#'
#' * `post_check`: A named vector of
#'    boolean values, of the same length
#'    as `fit`. Indicates whether the
#'    solution of each fit is
#'    admissible or not. Checked by
#'    [lavaan::lavInspect()] with
#'    the `what` argument set to
#'    `"post.check"`.
#'
#' @author Shu Fai Cheung <https://orcid.org/0000-0002-9871-9448>
#'
#' @examples
#' # To Do
#'
#' @export

fit_many <- function(model_list,
                     sem_out
                     ) {
  if (missing(model_list)) stop("model_list is not supplied.")
  if (missing(sem_out)) stop("sem_out is not supplied.")
  if (!inherits(sem_out, "lavaan")) {
      stop("sem_out is not a lavaan-class object.")
    }

  slot_opt <- sem_out@Options
  slot_pat <- sem_out@ParTable
  slot_mod <- sem_out@Model
  slot_smp <- sem_out@SampleStats
  slot_dat <- sem_out@Data
  slot_opt$se <- "none"

  fit_list <- lapply(model_list, function(x) {
                  lavaan::lavaan(model = x,
                                 slotOptions = slot_opt,
                                 slotSampleStats = slot_smp,
                                 slotData = slot_dat)
                })
  sem_out_df <- as.numeric(lavaan::fitMeasures(sem_out, "df"))
  change_list <- sapply(fit_list,
      function(x) sem_out_df - as.numeric(lavaan::fitMeasures(x, fit.measures = "df")))
  converged_list <- sapply(fit_list,
      function(x) lavaan::lavInspect(x, "converged"))
  post_check_list <- sapply(fit_list,
      function(x) lavaan::lavInspect(x, "post.check"))
  list(fit = fit_list,
       change = change_list,
       converged = converged_list,
       post_check = post_check_list)
}