#' @title Print a `partables`-Class Object
#'
#' @description Print the content of
#' an `partables`-class object
#'
#' @details Details
#'   (Include subjects for verbs.)
#'   (Use 3rd person forms for verbs.)
#'
#' @return
#' `x` is returned invisibly.
#' Called for its side effect.
#'
#' @param x A `partables`-class object.
#'
#' @param max_tables The maximum number
#' of modifications to be printed.
#' Default is 10.
#'
#' @param ...  Optional arguments.
#' Ignored.
#'
#'
#' @author Shu Fai Cheung <https://orcid.org/0000-0002-9871-9448>
#'
#' @seealso A `partables`-class object
#' is generated by `get_add()` and
#' `get_drop()`.
#'
#' @examples
#'
#' x <- 123
#' print(x)
#'
#' @export

print.partables <- function(x,
                            max_tables = 10,
                            ...) {
    x_n <- length(x)
    x_names <- names(x)
    x_1 <- x[[1]]
    x_call <- attr(x, "call")
    cat("\n")
    cat("Call:\n")
    print(x_call)
    cat("\n")
    cat("Number of parameter tables: ", x_n, "\n", sep = "")
    cat("\n")
    if (x_n > max_tables) {
        x_tmp <- x_names[seq_len(max_tables)]
        cat("The first", max_tables, "modification(s):\n")
      } else {
        x_tmp <- x_names
        cat("The modifications:\n")
      }
    cat(paste(x_tmp, collapse = "\n"), "\n")
    invisible(x)
  }