#' @title Print a `model_set`-Class Object
#'
#' @description Print the content of
#' an `model_set`-class object
#'
#' @details Details
#'   (Include subjects for verbs.)
#'   (Use 3rd person forms for verbs.)
#'
#' @return
#' `x` is returned invisibly.
#' Called for its side effect.
#'
#' @param x A `model_set`-class object.
#'
#' @param bic_digits The number of
#' decimal places to be displayed
#' for BIC.
#' Default is 3.
#'
#' @param bpp_digits The number of
#' decimal places to be displayed
#' for Bayesian posterior probability.
#' Default is 3.
#'
#' @param sort_models Whether the models
#' will be sorted by Bayesian posterior
#' probability.
#' Default is `TRUE`.
#'
#' @param max_models The maximum number
#' of models to be printed. Default is
#' 10.
#'
#' @param ...  Optional arguments.
#' Ignored.
#'
#' @author Shu Fai Cheung <https://orcid.org/0000-0002-9871-9448>
#'
#' @seealso A `model_set`-class object
#' is generated by `model_set()`.
#'
#' @examples
#'
#' library(lavaan)
#'
#' dat <- dat_path_model
#'
#' mod <-
#' "
#' x3 ~ a*x1 + b*x2
#' x4 ~ a*x1
#' ab := a*b
#' "
#'
#' fit <- sem(mod, dat_path_model, fixed.x = TRUE)
#'
#' out <- model_set(fit)
#' out
#'
#' @export

print.model_set <- function(x,
                            bic_digits = 3,
                            bpp_digits = 3,
                            sort_models = TRUE,
                            max_models = 10,
                            ...) {
    fit_n <- length(x$fit)
    fit_names <- names(x$fit)
    fit_many_call <- x$call
    model_set_call <- x$model_set_call
    k_converged <- sum(sapply(x$converged, isTRUE))
    k_post_check <- sum(sapply(x$post_check, isTRUE))
    out_table <- data.frame(modification = names(x$bic),
                            df = x$change,
                            BIC = x$bic,
                            BPP = x$postprob)
    if (sort_models) {
        i <- order(out_table$BPP,
                   decreasing = TRUE)
        out_table <- out_table[i, ]
        tmp <- round(cumsum(out_table$BPP), bpp_digits)
        tmp <- formatC(tmp,
                       digits = bpp_digits,
                       format = "f")
        out_table["BPP Cumulative"] <- tmp
      }
    out_table_print <- out_table
    out_table_print$BIC <- round(out_table_print$BIC,
                                 digits = bic_digits)
    out_table_print$BIC <- formatC(out_table_print$BIC,
                                   digits = bic_digits,
                                   format = "f")
    out_table_print$BPP <- round(out_table_print$BPP,
                                 digits = bpp_digits)
    out_table_print$BPP <- formatC(out_table_print$BPP,
                                   digits = bpp_digits,
                                   format = "f")
    if (fit_n > max_models) {
        x_tmp <- out_table_print[seq_len(max_models), ]
      } else {
        x_tmp <- out_table_print
      }
    cat("\n")
    cat("Call:\n")
    print(model_set_call)
    cat("\n")
    cat("Number of model(s) fitted: ", fit_n, "\n", sep = "")
    cat("Number of model(s) converged: ", k_converged, "\n", sep = "")
    cat("Number of model(s) passed post.check: ", k_post_check, "\n", sep = "")
    cat("\n")
    cat("\n")
    tmp1 <- ifelse(sort_models,
                   " (sorted by BPP)",
                   "")
    if (fit_n > max_models) {
        cat("The first ",
            max_models,
            " model(s)",
            tmp1,
            ":\n", sep = "")
      } else {
        cat("The models",
            tmp1,
            "\n", sep = "")
      }
    x_tmp$modification <- NULL
    print(x_tmp)
    cat("\nNote:\n")
    cat("- BIC: Bayesian Information Criterion.\n")
    cat("- BPP: Bayesian posterior probability.\n")
    if (sort_models) {
        cat("- BPP Cumulative: Cumulative Bayesian posterior probability.\n")
      }
    invisible(x)
  }